[metadata]
name = bidirectional-modeling
version = 0.12.0
description = A verifiable macro-purpose to micro-structure modeling reference framework
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
license_files = LICENSE

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
include_package_data = True

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    bidirectional-modeling = bidirectional_modeling.cli:main

[options.extras_require]
test =
    coverage>=7
    build>=1
