"""Verifiable bidirectional macro-purpose ↔ micro-structure modeling."""

from .correspondence import (
    Correspondence,
    CorrespondenceCaseResult,
    CorrespondenceCaseRole,
    CorrespondenceCertificate,
    CorrespondenceCounterexample,
    CorrespondenceSuiteCertificate,
    CorrespondenceValidationCase,
    CorrespondenceValidator,
    Scale,
    ScaleGraph,
    ScalePath,
    context_fingerprint,
)
from .core import (
    Aggregation,
    CandidateEvaluation,
    CheckResult,
    ClosureReport,
    Concept,
    ConfidenceBreakdown,
    Context,
    Counterexample,
    CustomRequirement,
    DiscriminatingQuery,
    EquivalenceSpec,
    Evidence,
    Experiment,
    FieldRequirement,
    FiniteStateModel,
    InterpretationCandidate,
    InterpretationResult,
    Intervention,
    MacroSpec,
    ModelMetricRequirement,
    ModelMetrics,
    PurposeHypothesis,
    PurposeLevel,
    ProbeOutcome,
    RealizationResult,
    RequirementCategory,
    ResourceBudget,
    ScenarioKey,
    SatisfactionCertificate,
    Trace,
)
from .engine import (
    BidirectionalModelingEngine,
    MacroRoundTripReport,
    MicroRoundTripReport,
    RefinementLoopReport,
    RefinementStep,
    behaviorally_equivalent,
)
from .evaluation import SatisfactionEvaluator, TraceBatch
from .interpretation import (
    CatalogHypothesisGenerator,
    HypothesisGenerator,
    InterpretationScoringPolicy,
    Interpreter,
    ObservedEffectGenerator,
)
from .probes import HorizonExtensionProbe
from .realization import (
    CandidateGenerator,
    ParametricCandidateGenerator,
    Realizer,
    RedTeamProbe,
    RegistryGenerator,
    pareto_partition,
)
from .refinement import ClosureAnalyzer, ConceptLibrary

__all__ = [
    "Aggregation",
    "BidirectionalModelingEngine",
    "CandidateEvaluation",
    "CandidateGenerator",
    "CatalogHypothesisGenerator",
    "CheckResult",
    "ClosureAnalyzer",
    "ClosureReport",
    "Concept",
    "ConceptLibrary",
    "ConfidenceBreakdown",
    "Context",
    "Correspondence",
    "CorrespondenceCaseResult",
    "CorrespondenceCaseRole",
    "CorrespondenceCertificate",
    "CorrespondenceCounterexample",
    "CorrespondenceSuiteCertificate",
    "CorrespondenceValidationCase",
    "CorrespondenceValidator",
    "Counterexample",
    "CustomRequirement",
    "DiscriminatingQuery",
    "EquivalenceSpec",
    "Evidence",
    "Experiment",
    "FieldRequirement",
    "FiniteStateModel",
    "HorizonExtensionProbe",
    "HypothesisGenerator",
    "InterpretationCandidate",
    "InterpretationResult",
    "Interpreter",
    "Intervention",
    "MacroRoundTripReport",
    "MacroSpec",
    "MicroRoundTripReport",
    "ModelMetricRequirement",
    "ModelMetrics",
    "ObservedEffectGenerator",
    "ParametricCandidateGenerator",
    "PurposeHypothesis",
    "PurposeLevel",
    "ProbeOutcome",
    "RealizationResult",
    "Realizer",
    "RedTeamProbe",
    "RegistryGenerator",
    "RefinementLoopReport",
    "RefinementStep",
    "RequirementCategory",
    "ResourceBudget",
    "Scale",
    "ScaleGraph",
    "ScalePath",
    "ScenarioKey",
    "SatisfactionCertificate",
    "SatisfactionEvaluator",
    "Trace",
    "TraceBatch",
    "InterpretationScoringPolicy",
    "behaviorally_equivalent",
    "context_fingerprint",
    "pareto_partition",
]

__version__ = "0.6.0"
