"""Verifiable bidirectional macro-purpose ↔ micro-structure modeling."""

from .core import (
    Aggregation,
    CandidateEvaluation,
    CheckResult,
    ClosureReport,
    Concept,
    ConfidenceBreakdown,
    Context,
    Counterexample,
    CustomRequirement,
    DiscriminatingQuery,
    EquivalenceSpec,
    Evidence,
    Experiment,
    FieldRequirement,
    FiniteStateModel,
    InterpretationCandidate,
    InterpretationResult,
    Intervention,
    MacroSpec,
    ModelMetricRequirement,
    ModelMetrics,
    PurposeHypothesis,
    PurposeLevel,
    RealizationResult,
    RequirementCategory,
    ResourceBudget,
    SatisfactionCertificate,
    Trace,
)
from .engine import (
    BidirectionalModelingEngine,
    MacroRoundTripReport,
    MicroRoundTripReport,
    behaviorally_equivalent,
)
from .evaluation import SatisfactionEvaluator
from .interpretation import (
    CatalogHypothesisGenerator,
    HypothesisGenerator,
    Interpreter,
    ObservedEffectGenerator,
)
from .probes import HorizonExtensionProbe
from .realization import (
    CandidateGenerator,
    ParametricCandidateGenerator,
    Realizer,
    RedTeamProbe,
    RegistryGenerator,
    pareto_partition,
)
from .refinement import ClosureAnalyzer, ConceptLibrary

__all__ = [
    "Aggregation",
    "BidirectionalModelingEngine",
    "CandidateEvaluation",
    "CandidateGenerator",
    "CatalogHypothesisGenerator",
    "CheckResult",
    "ClosureAnalyzer",
    "ClosureReport",
    "Concept",
    "ConceptLibrary",
    "ConfidenceBreakdown",
    "Context",
    "Counterexample",
    "CustomRequirement",
    "DiscriminatingQuery",
    "EquivalenceSpec",
    "Evidence",
    "Experiment",
    "FieldRequirement",
    "FiniteStateModel",
    "HorizonExtensionProbe",
    "HypothesisGenerator",
    "InterpretationCandidate",
    "InterpretationResult",
    "Interpreter",
    "Intervention",
    "MacroRoundTripReport",
    "MacroSpec",
    "MicroRoundTripReport",
    "ModelMetricRequirement",
    "ModelMetrics",
    "ObservedEffectGenerator",
    "ParametricCandidateGenerator",
    "PurposeHypothesis",
    "PurposeLevel",
    "RealizationResult",
    "Realizer",
    "RedTeamProbe",
    "RegistryGenerator",
    "RequirementCategory",
    "ResourceBudget",
    "SatisfactionCertificate",
    "SatisfactionEvaluator",
    "Trace",
    "behaviorally_equivalent",
    "pareto_partition",
]

__version__ = "0.1.0"

